name: Show requirements

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  show-requirements:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: List repository files
      run: ls -la

    - name: Display requirements.txt
      run: cat requirements.txt
